spring:
  application:
    name: eureka-server
  profiles:
    active: stage
  #main:
   # allow-bean-definition-overriding: true



---
spring:
  profiles: localhost
  
eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
      
name: local-YAML
server:
  port: 8763  
---
spring:
  profiles: stage

eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka
      
name: stage-YAML
server:
  port: 8764
---
spring:
  profiles: prod

eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

name: prod-YAML
server:
  port: 8765
